---
prepare:
  - git diff-index --quiet HEAD --
  - git checkout master
  - git pull --rebase
  - check-node-version --node $(cat .nvmrc) --yarn 1.7
  - ROLLBACK_COMMIT_ID=$(git rev-parse HEAD)
  - yarn install

test:
  - yarn travis

build:
  - yarn build
  - git add dist/bundle.js
  - git commit -m "Update build file"

after_publish:
  - 'git push --follow-tags origin master:master'

after_failure:
  - '[[ ! -z "$ROLLBACK_COMMIT_ID" ]] && git reset --hard $ROLLBACK_COMMIT_ID'
  - unset ROLLBACK_COMMIT_ID

changelog:
  - offline-github-changelog > CHANGELOG.md
  - git add CHANGELOG.md
  - git commit --allow-empty -m "Update changelog"
  - 'git push origin master:master'

after_success:
  - unset ROLLBACK_COMMIT_ID
