---
rollback: true

prepare:
  - git diff-index --quiet HEAD --
  - git checkout master
  - git pull --rebase
  - '[[ -f .nvmrc ]] && check-node-version --node $(cat .nvmrc) --yarn 1.7'
  - yarn install

test:
  - yarn travis

after_publish:
  - 'git push --follow-tags origin master:master'

changelog:
  - npx offline-github-changelog > CHANGELOG.md
  - git add CHANGELOG.md
  - git commit --allow-empty -m "Update changelog"
  - 'git push origin master:master'
