name: repo-checks
on: [push]
jobs:
  main:
    name: yarn-simple
    runs-on: ubuntu-latest
    steps:
    - uses: zendesk/checkout@v2
    - uses: zendesk/setup-node@v2.0.0
      with:
        node-version: 10.16.0 
    - name: yarn test
      run: |
        yarn install
        yarn travis

